<!-- ===== GLOBAL STATUS CONFIRMATION MODAL ===== -->
<div class="modal fade" id="globalStatusModal" tabindex="-1"
    aria-labelledby="globalStatusModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content" style="border-radius:14px; border:none; box-shadow:0 16px 48px rgba(0,0,0,0.18);">
            <div class="modal-header border-0 pb-0">
                <h6 class="modal-title fw-bold" id="globalStatusModalLabel">
                    <i class="fas fa-shield-alt text-primary me-2"></i>Konfirmasi Perubahan Status
                </h6>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Tutup"></button>
            </div>
            <div class="modal-body text-center py-4">
                <div id="globalModalIconWrap" class="mb-3 mx-auto"
                    style="width:68px;height:68px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:1.9rem;">
                </div>
                <p class="mb-1 fw-bold" style="font-size:1rem;">Ubah status menjadi</p>
                <h5 id="globalModalStatusText" class="fw-bold mb-3"></h5>
                <p class="text-muted" style="font-size:0.85rem;" id="globalModalStatusMsg">
                    Status data akan diperbarui. Pastikan keputusan ini sudah benar.
                </p>
            </div>
            <div class="modal-footer border-0 justify-content-center gap-2 pt-0">
                <button type="button" class="btn btn-light px-4" data-bs-dismiss="modal">
                    <i class="fas fa-times me-1"></i>Batal
                </button>
                <form id="globalUpdateStatusForm" method="POST" action="">
                    <!-- CSRF Field usually generated by CI4, but in global modal it's safer to have it if we need it. 
                         Since we are moving it, we just use standard CI4 csrf_field() -->
                    <?= csrf_field() ?>
                    <button type="submit" id="globalModalConfirmBtn" class="btn px-4 fw-bold">
                        <i class="fas fa-check me-1"></i>Ya, Ubah Sekarang
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        var globalStatusModal = document.getElementById('globalStatusModal');
        if (globalStatusModal) {
            globalStatusModal.addEventListener('show.bs.modal', function(event) {
                var btn = event.relatedTarget;
                var newStatus = btn.getAttribute('data-status');
                var statusLabel = btn.getAttribute('data-status-label');
                var color = btn.getAttribute('data-color');
                var icon = btn.getAttribute('data-icon');
                var url = btn.getAttribute('data-status-url');
                var msg = btn.getAttribute('data-status-msg');

                // Set form action (base url + newStatus)
                if (url) {
                    var actionUrl = url.endsWith('/') ? url + newStatus : url + '/' + newStatus;
                    document.getElementById('globalUpdateStatusForm').action = actionUrl;
                }

                if (msg) {
                    document.getElementById('globalModalStatusMsg').innerHTML = msg;
                }

                // Color mapping
                var colorMap = {
                    success: { bg: '#d1e7dd', color: '#0a5c36' },
                    warning: { bg: '#fff3cd', color: '#7d5a00' },
                    danger:  { bg: '#f8d7da', color: '#842029' },
                    dark:    { bg: '#dee2e6', color: '#212529' },
                };
                var c = colorMap[color] || { bg: '#e7f0ff', color: '#0d6efd' };

                var iconWrap = document.getElementById('globalModalIconWrap');
                iconWrap.style.background = c.bg;
                iconWrap.style.color = c.color;
                iconWrap.innerHTML = '<i class="' + icon + '"></i>';

                var label = document.getElementById('globalModalStatusText');
                label.textContent = statusLabel;
                label.style.color = c.color;

                document.getElementById('globalModalConfirmBtn').className = 'btn btn-' + color + ' px-4 fw-bold';
            });

            /* Loading spinner on submit */
            document.getElementById('globalUpdateStatusForm').addEventListener('submit', function() {
                var btn = this.querySelector('button[type="submit"]');
                btn.disabled = true;
                btn.innerHTML = '<span class="spinner-border spinner-border-sm me-1" role="status" aria-hidden="true"></span> Menyimpan...';
            });
        }
    });
</script>
