<?php

namespace App\Controllers\Api;

use App\Controllers\BaseController;
use CodeIgniter\API\ResponseTrait;

class UnityApi extends BaseController
{
    use ResponseTrait;

    protected $db;

    public function __construct()
    {
        $this->db = \Config\Database::connect();
    }

    /**
     * Mendapatkan data construction_rabs berdasarkan construction_requests.id
     * 
     * GET /api/unity/construction-rabs/{constructionRequestId}
     * 
     * @param int|null $constructionRequestId
     * @return \CodeIgniter\HTTP\Response
     */
    public function getRabByConstructionId($constructionRequestId = null)
    {
        if ($constructionRequestId === null) {
            return $this->fail('Construction Request ID tidak boleh kosong.');
        }

        try {
            // Ambil data RAB konstruksi
            $jsonString = <<<'JSON'
{
    "status": true,
    "message": "Detail RAB Proyek konstruksi ditemukan",
    "data": [
        {
            "id": "71",
            "construction_id": "44",
            "roman_number": "I",
            "group_name": "PEKERJAAN PERSIAPAN",
            "sub_group_name": "",
            "section_group": "",
            "section_name": "",
            "activity_name": "Persiapan & Pembersihan",
            "volume": "1.00",
            "unit": "Ls",
            "selected_material_id": null,
            "current_unit_price": "2000000.0000",
            "total_price": "2000000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "72",
            "construction_id": "44",
            "roman_number": "II",
            "group_name": "PEKERJAAN TANAH",
            "sub_group_name": "",
            "section_group": "",
            "section_name": "",
            "activity_name": "Penggalian 1 m3 Tanah Biasa Sedalam 2 m",
            "volume": "22.50",
            "unit": "m3",
            "selected_material_id": null,
            "current_unit_price": "67500.0000",
            "total_price": "1518750.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "73",
            "construction_id": "44",
            "roman_number": "II",
            "group_name": "PEKERJAAN TANAH",
            "sub_group_name": "",
            "section_group": "",
            "section_name": "",
            "activity_name": "Urugan Tanah Kembali",
            "volume": "6.75",
            "unit": "m3",
            "selected_material_id": null,
            "current_unit_price": "37500.0000",
            "total_price": "253125.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "74",
            "construction_id": "44",
            "roman_number": "II",
            "group_name": "PEKERJAAN TANAH",
            "sub_group_name": "",
            "section_group": "",
            "section_name": "",
            "activity_name": "Pasir Urug bawah pondasi",
            "volume": "1.31",
            "unit": "m3",
            "selected_material_id": null,
            "current_unit_price": "322500.0000",
            "total_price": "422475.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "75",
            "construction_id": "44",
            "roman_number": "III",
            "group_name": "STRUKTUR",
            "sub_group_name": "1 PONDASI BATU BELAH",
            "section_group": "1 PONDASI BATU BELAH",
            "section_name": "1 PONDASI BATU BELAH",
            "activity_name": "Batu Belah",
            "volume": "10.13",
            "unit": "m3",
            "selected_material_id": null,
            "current_unit_price": "709750.0000",
            "total_price": "7189767.5000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "76",
            "construction_id": "44",
            "roman_number": "III",
            "group_name": "STRUKTUR",
            "sub_group_name": "1 PONDASI BATU BELAH",
            "section_group": "1 PONDASI BATU BELAH",
            "section_name": "1 PONDASI BATU BELAH",
            "activity_name": "Aanstamping PB1",
            "volume": "5.25",
            "unit": "m3",
            "selected_material_id": null,
            "current_unit_price": "503550.0000",
            "total_price": "2643637.5000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "77",
            "construction_id": "44",
            "roman_number": "III",
            "group_name": "STRUKTUR",
            "sub_group_name": "1 PONDASI BATU BELAH",
            "section_group": "1 PONDASI BATU BELAH",
            "section_name": "1 PONDASI BATU BELAH",
            "activity_name": "Lantai Kerja 10 cm",
            "volume": "6.30",
            "unit": "m3",
            "selected_material_id": null,
            "current_unit_price": "770467.8600",
            "total_price": "4853947.5180",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "78",
            "construction_id": "44",
            "roman_number": "III",
            "group_name": "STRUKTUR",
            "sub_group_name": "2 Kolom K1 15/30 K250",
            "section_group": "2 Kolom K1 15/30 K250",
            "section_name": "2 Kolom K1 15/30 K250",
            "activity_name": "Beton K250",
            "volume": "2.16",
            "unit": "m3",
            "selected_material_id": null,
            "current_unit_price": "916989.5500",
            "total_price": "1980697.4280",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "79",
            "construction_id": "44",
            "roman_number": "III",
            "group_name": "STRUKTUR",
            "sub_group_name": "2 Kolom K1 15/30 K250",
            "section_group": "2 Kolom K1 15/30 K250",
            "section_name": "2 Kolom K1 15/30 K250",
            "activity_name": "Pembesian",
            "volume": "328.32",
            "unit": "kg",
            "selected_material_id": null,
            "current_unit_price": "13250.0000",
            "total_price": "4350240.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "80",
            "construction_id": "44",
            "roman_number": "III",
            "group_name": "STRUKTUR",
            "sub_group_name": "2 Kolom K1 15/30 K250",
            "section_group": "2 Kolom K1 15/30 K250",
            "section_name": "2 Kolom K1 15/30 K250",
            "activity_name": "Bekisting 2X pakai",
            "volume": "43.83",
            "unit": "m2",
            "selected_material_id": null,
            "current_unit_price": "129800.0000",
            "total_price": "5689134.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "81",
            "construction_id": "44",
            "roman_number": "III",
            "group_name": "STRUKTUR",
            "sub_group_name": "3 Kolom Kp 15/15 K250",
            "section_group": "3 Kolom Kp 15/15 K250",
            "section_name": "3 Kolom Kp 15/15 K250",
            "activity_name": "Beton K250",
            "volume": "0.88",
            "unit": "m3",
            "selected_material_id": null,
            "current_unit_price": "916989.5500",
            "total_price": "806950.8040",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "82",
            "construction_id": "44",
            "roman_number": "III",
            "group_name": "STRUKTUR",
            "sub_group_name": "3 Kolom Kp 15/15 K250",
            "section_group": "3 Kolom Kp 15/15 K250",
            "section_name": "3 Kolom Kp 15/15 K250",
            "activity_name": "Pembesian",
            "volume": "167.95",
            "unit": "kg",
            "selected_material_id": null,
            "current_unit_price": "13250.0000",
            "total_price": "2225337.5000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "83",
            "construction_id": "44",
            "roman_number": "III",
            "group_name": "STRUKTUR",
            "sub_group_name": "3 Kolom Kp 15/15 K250",
            "section_group": "3 Kolom Kp 15/15 K250",
            "section_name": "3 Kolom Kp 15/15 K250",
            "activity_name": "Bekisting 2X pakai",
            "volume": "23.69",
            "unit": "m2",
            "selected_material_id": null,
            "current_unit_price": "129800.0000",
            "total_price": "3074962.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "84",
            "construction_id": "44",
            "roman_number": "III",
            "group_name": "STRUKTUR",
            "sub_group_name": "4 Sloof S1 15/20 K250",
            "section_group": "4 Sloof S1 15/20 K250",
            "section_name": "4 Sloof S1 15/20 K250",
            "activity_name": "Beton K250",
            "volume": "2.16",
            "unit": "m3",
            "selected_material_id": null,
            "current_unit_price": "916989.5500",
            "total_price": "1980697.4280",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "85",
            "construction_id": "44",
            "roman_number": "III",
            "group_name": "STRUKTUR",
            "sub_group_name": "4 Sloof S1 15/20 K250",
            "section_group": "4 Sloof S1 15/20 K250",
            "section_name": "4 Sloof S1 15/20 K250",
            "activity_name": "Pembesian",
            "volume": "540.60",
            "unit": "kg",
            "selected_material_id": null,
            "current_unit_price": "13250.0000",
            "total_price": "7162950.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "86",
            "construction_id": "44",
            "roman_number": "III",
            "group_name": "STRUKTUR",
            "sub_group_name": "4 Sloof S1 15/20 K250",
            "section_group": "4 Sloof S1 15/20 K250",
            "section_name": "4 Sloof S1 15/20 K250",
            "activity_name": "Bekisting 2X pakai",
            "volume": "50.55",
            "unit": "m2",
            "selected_material_id": null,
            "current_unit_price": "112150.0000",
            "total_price": "5669182.5000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "87",
            "construction_id": "44",
            "roman_number": "III",
            "group_name": "STRUKTUR",
            "sub_group_name": "5 RB1 15/20 K250",
            "section_group": "5 RB1 15/20 K250",
            "section_name": "5 RB1 15/20 K250",
            "activity_name": "Beton K250",
            "volume": "2.42",
            "unit": "m3",
            "selected_material_id": null,
            "current_unit_price": "916989.5500",
            "total_price": "2219114.7110",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "88",
            "construction_id": "44",
            "roman_number": "III",
            "group_name": "STRUKTUR",
            "sub_group_name": "5 RB1 15/20 K250",
            "section_group": "5 RB1 15/20 K250",
            "section_name": "5 RB1 15/20 K250",
            "activity_name": "Pembesian",
            "volume": "239.38",
            "unit": "kg",
            "selected_material_id": null,
            "current_unit_price": "13250.0000",
            "total_price": "3171785.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "89",
            "construction_id": "44",
            "roman_number": "III",
            "group_name": "STRUKTUR",
            "sub_group_name": "5 RB1 15/20 K250",
            "section_group": "5 RB1 15/20 K250",
            "section_name": "5 RB1 15/20 K250",
            "activity_name": "Bekisting 2X pakai",
            "volume": "56.57",
            "unit": "m2",
            "selected_material_id": null,
            "current_unit_price": "273100.0000",
            "total_price": "15449267.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "90",
            "construction_id": "44",
            "roman_number": "III",
            "group_name": "STRUKTUR",
            "sub_group_name": "6 Slab S1 K250",
            "section_group": "6 Slab S1 K250",
            "section_name": "6 Slab S1 K250",
            "activity_name": "Beton K250",
            "volume": "0.64",
            "unit": "m3",
            "selected_material_id": null,
            "current_unit_price": "916989.5500",
            "total_price": "586873.3120",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "91",
            "construction_id": "44",
            "roman_number": "III",
            "group_name": "STRUKTUR",
            "sub_group_name": "6 Slab S1 K250",
            "section_group": "6 Slab S1 K250",
            "section_name": "6 Slab S1 K250",
            "activity_name": "Besi D13",
            "volume": "112.57",
            "unit": "kg",
            "selected_material_id": null,
            "current_unit_price": "13250.0000",
            "total_price": "1491552.5000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "92",
            "construction_id": "44",
            "roman_number": "III",
            "group_name": "STRUKTUR",
            "sub_group_name": "6 Slab S1 K250",
            "section_group": "6 Slab S1 K250",
            "section_name": "6 Slab S1 K250",
            "activity_name": "Bekisting",
            "volume": "8.03",
            "unit": "m2",
            "selected_material_id": null,
            "current_unit_price": "319600.0000",
            "total_price": "2566388.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "93",
            "construction_id": "44",
            "roman_number": "IV",
            "group_name": "ARSITEK",
            "sub_group_name": "1 PEKERJAAN PENUTUP LANTAI & DINDING",
            "section_group": "1 PEKERJAAN PENUTUP LANTAI & DINDING",
            "section_name": "1 PEKERJAAN PENUTUP LANTAI & DINDING",
            "activity_name": "Granit 60x60cm Polos Glossy",
            "volume": "42.60",
            "unit": "m2",
            "selected_material_id": null,
            "current_unit_price": "450000.0000",
            "total_price": "19170000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "94",
            "construction_id": "44",
            "roman_number": "IV",
            "group_name": "ARSITEK",
            "sub_group_name": "1 PEKERJAAN PENUTUP LANTAI & DINDING",
            "section_group": "1 PEKERJAAN PENUTUP LANTAI & DINDING",
            "section_name": "1 PEKERJAAN PENUTUP LANTAI & DINDING",
            "activity_name": "Granit 60x60cm Wood Looks Matte",
            "volume": "4.45",
            "unit": "m2",
            "selected_material_id": null,
            "current_unit_price": "375000.0000",
            "total_price": "1668750.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "95",
            "construction_id": "44",
            "roman_number": "IV",
            "group_name": "ARSITEK",
            "sub_group_name": "1 PEKERJAAN PENUTUP LANTAI & DINDING",
            "section_group": "1 PEKERJAAN PENUTUP LANTAI & DINDING",
            "section_name": "1 PEKERJAAN PENUTUP LANTAI & DINDING",
            "activity_name": "Granit 40x40cm Anti Slip",
            "volume": "7.95",
            "unit": "m2",
            "selected_material_id": null,
            "current_unit_price": "355000.0000",
            "total_price": "2822250.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "96",
            "construction_id": "44",
            "roman_number": "IV",
            "group_name": "ARSITEK",
            "sub_group_name": "1 PEKERJAAN PENUTUP LANTAI & DINDING",
            "section_group": "1 PEKERJAAN PENUTUP LANTAI & DINDING",
            "section_name": "1 PEKERJAAN PENUTUP LANTAI & DINDING",
            "activity_name": "Paving block 200x100 Light to dark Grey Natural",
            "volume": "14.75",
            "unit": "m2",
            "selected_material_id": null,
            "current_unit_price": "300000.0000",
            "total_price": "4425000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "97",
            "construction_id": "44",
            "roman_number": "IV",
            "group_name": "ARSITEK",
            "sub_group_name": "1 PEKERJAAN PENUTUP LANTAI & DINDING",
            "section_group": "1 PEKERJAAN PENUTUP LANTAI & DINDING",
            "section_name": "1 PEKERJAAN PENUTUP LANTAI & DINDING",
            "activity_name": "Plint Granit 60x60cm Polos Glossy",
            "volume": "66.35",
            "unit": "m2",
            "selected_material_id": null,
            "current_unit_price": "75000.0000",
            "total_price": "4976250.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "98",
            "construction_id": "44",
            "roman_number": "IV",
            "group_name": "ARSITEK",
            "sub_group_name": "1 PEKERJAAN PENUTUP LANTAI & DINDING",
            "section_group": "1 PEKERJAAN PENUTUP LANTAI & DINDING",
            "section_name": "1 PEKERJAAN PENUTUP LANTAI & DINDING",
            "activity_name": "Plint Granit 60x60cm Wood Looks Matte",
            "volume": "13.30",
            "unit": "m2",
            "selected_material_id": null,
            "current_unit_price": "62500.0000",
            "total_price": "831250.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "99",
            "construction_id": "44",
            "roman_number": "IV",
            "group_name": "ARSITEK",
            "sub_group_name": "2 PEKERJAAN PENUTUP LANGIT - LANGIT PLAFOND",
            "section_group": "2 PEKERJAAN PENUTUP LANGIT - LANGIT PLAFOND",
            "section_name": "2 PEKERJAAN PENUTUP LANGIT - LANGIT PLAFOND",
            "activity_name": "Plafond Gypsum Board",
            "volume": "70.50",
            "unit": "m2",
            "selected_material_id": null,
            "current_unit_price": "84600.0000",
            "total_price": "5964300.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "100",
            "construction_id": "44",
            "roman_number": "IV",
            "group_name": "ARSITEK",
            "sub_group_name": "2 PEKERJAAN PENUTUP LANGIT - LANGIT PLAFOND",
            "section_group": "2 PEKERJAAN PENUTUP LANGIT - LANGIT PLAFOND",
            "section_name": "2 PEKERJAAN PENUTUP LANGIT - LANGIT PLAFOND",
            "activity_name": "Rangka Hollow 4x4/2x4",
            "volume": "87.00",
            "unit": "m2",
            "selected_material_id": null,
            "current_unit_price": "77075.0000",
            "total_price": "6705525.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "101",
            "construction_id": "44",
            "roman_number": "IV",
            "group_name": "ARSITEK",
            "sub_group_name": "2 PEKERJAAN PENUTUP LANGIT - LANGIT PLAFOND",
            "section_group": "2 PEKERJAAN PENUTUP LANGIT - LANGIT PLAFOND",
            "section_name": "2 PEKERJAAN PENUTUP LANGIT - LANGIT PLAFOND",
            "activity_name": "List Plafond Gypsum",
            "volume": "122.00",
            "unit": "m'",
            "selected_material_id": null,
            "current_unit_price": "15525.0000",
            "total_price": "1894050.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "102",
            "construction_id": "44",
            "roman_number": "IV",
            "group_name": "ARSITEK",
            "sub_group_name": "2 PEKERJAAN PENUTUP LANGIT - LANGIT PLAFOND",
            "section_group": "2 PEKERJAAN PENUTUP LANGIT - LANGIT PLAFOND",
            "section_name": "2 PEKERJAAN PENUTUP LANGIT - LANGIT PLAFOND",
            "activity_name": "Memasang Langit Langit PVC Board",
            "volume": "16.50",
            "unit": "m2",
            "selected_material_id": null,
            "current_unit_price": "169200.0000",
            "total_price": "2791800.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "103",
            "construction_id": "44",
            "roman_number": "IV",
            "group_name": "ARSITEK",
            "sub_group_name": "3 PEKERJAAN PASANGAN DINDING",
            "section_group": "3 PEKERJAAN PASANGAN DINDING",
            "section_name": "3 PEKERJAAN PASANGAN DINDING",
            "activity_name": "Pas Dinding Hebel",
            "volume": "212.11",
            "unit": "m2",
            "selected_material_id": null,
            "current_unit_price": "114411.0500",
            "total_price": "24267727.8155",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "104",
            "construction_id": "44",
            "roman_number": "IV",
            "group_name": "ARSITEK",
            "sub_group_name": "3 PEKERJAAN PASANGAN DINDING",
            "section_group": "3 PEKERJAAN PASANGAN DINDING",
            "section_name": "3 PEKERJAAN PASANGAN DINDING",
            "activity_name": "Pekerjaan Plester + Aci",
            "volume": "424.22",
            "unit": "m2",
            "selected_material_id": null,
            "current_unit_price": "72588.0000",
            "total_price": "30793281.3600",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "105",
            "construction_id": "44",
            "roman_number": "IV",
            "group_name": "ARSITEK",
            "sub_group_name": "3 PEKERJAAN PASANGAN DINDING",
            "section_group": "3 PEKERJAAN PASANGAN DINDING",
            "section_name": "3 PEKERJAAN PASANGAN DINDING",
            "activity_name": "Pekerjaan Cat Dinding",
            "volume": "424.22",
            "unit": "m2",
            "selected_material_id": null,
            "current_unit_price": "30005.0000",
            "total_price": "12728721.1000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "106",
            "construction_id": "44",
            "roman_number": "IV",
            "group_name": "ARSITEK",
            "sub_group_name": "3 PEKERJAAN PASANGAN DINDING",
            "section_group": "3 PEKERJAAN PASANGAN DINDING",
            "section_name": "3 PEKERJAAN PASANGAN DINDING",
            "activity_name": "Dinding roaster",
            "volume": "9.76",
            "unit": "m2",
            "selected_material_id": null,
            "current_unit_price": "231600.0000",
            "total_price": "2260416.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "107",
            "construction_id": "44",
            "roman_number": "IV",
            "group_name": "ARSITEK",
            "sub_group_name": "4 PEKERJAAN DAUN PINTU DAN JENDELA",
            "section_group": "4 PEKERJAAN DAUN PINTU DAN JENDELA",
            "section_name": "4 PEKERJAAN DAUN PINTU DAN JENDELA",
            "activity_name": "Pintu Utama",
            "volume": "3.00",
            "unit": "unit",
            "selected_material_id": null,
            "current_unit_price": "6500000.0000",
            "total_price": "19500000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "108",
            "construction_id": "44",
            "roman_number": "IV",
            "group_name": "ARSITEK",
            "sub_group_name": "4 PEKERJAAN DAUN PINTU DAN JENDELA",
            "section_group": "4 PEKERJAAN DAUN PINTU DAN JENDELA",
            "section_name": "4 PEKERJAAN DAUN PINTU DAN JENDELA",
            "activity_name": "Pintu Kamar",
            "volume": "2.00",
            "unit": "unit",
            "selected_material_id": null,
            "current_unit_price": "3500000.0000",
            "total_price": "7000000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "109",
            "construction_id": "44",
            "roman_number": "IV",
            "group_name": "ARSITEK",
            "sub_group_name": "4 PEKERJAAN DAUN PINTU DAN JENDELA",
            "section_group": "4 PEKERJAAN DAUN PINTU DAN JENDELA",
            "section_name": "4 PEKERJAAN DAUN PINTU DAN JENDELA",
            "activity_name": "Pintu Kamar Mandi Alluminium",
            "volume": "1.00",
            "unit": "unit",
            "selected_material_id": null,
            "current_unit_price": "1750000.0000",
            "total_price": "1750000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "110",
            "construction_id": "44",
            "roman_number": "IV",
            "group_name": "ARSITEK",
            "sub_group_name": "4 PEKERJAAN DAUN PINTU DAN JENDELA",
            "section_group": "4 PEKERJAAN DAUN PINTU DAN JENDELA",
            "section_name": "4 PEKERJAAN DAUN PINTU DAN JENDELA",
            "activity_name": "Jendela Alluminium J2",
            "volume": "3.00",
            "unit": "m2",
            "selected_material_id": null,
            "current_unit_price": "2850000.0000",
            "total_price": "8550000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "111",
            "construction_id": "44",
            "roman_number": "IV",
            "group_name": "ARSITEK",
            "sub_group_name": "4 PEKERJAAN DAUN PINTU DAN JENDELA",
            "section_group": "4 PEKERJAAN DAUN PINTU DAN JENDELA",
            "section_name": "4 PEKERJAAN DAUN PINTU DAN JENDELA",
            "activity_name": "Jendela Alluminium J1 bouven",
            "volume": "3.00",
            "unit": "m2",
            "selected_material_id": null,
            "current_unit_price": "2850000.0000",
            "total_price": "8550000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "112",
            "construction_id": "44",
            "roman_number": "IV",
            "group_name": "ARSITEK",
            "sub_group_name": "4 PEKERJAAN DAUN PINTU DAN JENDELA",
            "section_group": "4 PEKERJAAN DAUN PINTU DAN JENDELA",
            "section_name": "4 PEKERJAAN DAUN PINTU DAN JENDELA",
            "activity_name": "Pintu sledding alluminium",
            "volume": "6.00",
            "unit": "m2",
            "selected_material_id": null,
            "current_unit_price": "3500000.0000",
            "total_price": "21000000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "113",
            "construction_id": "44",
            "roman_number": "IV",
            "group_name": "ARSITEK",
            "sub_group_name": "5 PEKERJAAN RANGKA + ATAP",
            "section_group": "5 PEKERJAAN RANGKA + ATAP",
            "section_name": "5 PEKERJAAN RANGKA + ATAP",
            "activity_name": "Lisplang tempel Atap",
            "volume": "8.00",
            "unit": "m'",
            "selected_material_id": null,
            "current_unit_price": "125000.0000",
            "total_price": "1000000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "114",
            "construction_id": "44",
            "roman_number": "IV",
            "group_name": "ARSITEK",
            "sub_group_name": "5 PEKERJAAN RANGKA + ATAP",
            "section_group": "5 PEKERJAAN RANGKA + ATAP",
            "section_name": "5 PEKERJAAN RANGKA + ATAP",
            "activity_name": "Rangka Atap Baja Ringan",
            "volume": "67.00",
            "unit": "m2",
            "selected_material_id": null,
            "current_unit_price": "169900.0000",
            "total_price": "11383300.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "115",
            "construction_id": "44",
            "roman_number": "IV",
            "group_name": "ARSITEK",
            "sub_group_name": "5 PEKERJAAN RANGKA + ATAP",
            "section_group": "5 PEKERJAAN RANGKA + ATAP",
            "section_name": "5 PEKERJAAN RANGKA + ATAP",
            "activity_name": "Atap Spandek berpasir",
            "volume": "67.00",
            "unit": "m2",
            "selected_material_id": null,
            "current_unit_price": "133100.0000",
            "total_price": "8917700.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "116",
            "construction_id": "44",
            "roman_number": "V",
            "group_name": "MEP",
            "sub_group_name": "1 PEKERJAAN INSTALASI LISTRIK",
            "section_group": "1 PEKERJAAN INSTALASI LISTRIK",
            "section_name": "1 PEKERJAAN INSTALASI LISTRIK",
            "activity_name": "Instalasi Titik Lampu + Pipa Conduit",
            "volume": "20.00",
            "unit": "unit",
            "selected_material_id": null,
            "current_unit_price": "175000.0000",
            "total_price": "3500000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "117",
            "construction_id": "44",
            "roman_number": "V",
            "group_name": "MEP",
            "sub_group_name": "1 PEKERJAAN INSTALASI LISTRIK",
            "section_group": "1 PEKERJAAN INSTALASI LISTRIK",
            "section_name": "1 PEKERJAAN INSTALASI LISTRIK",
            "activity_name": "Downlight LED 10 watt",
            "volume": "19.00",
            "unit": "unit",
            "selected_material_id": null,
            "current_unit_price": "125000.0000",
            "total_price": "2375000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "118",
            "construction_id": "44",
            "roman_number": "V",
            "group_name": "MEP",
            "sub_group_name": "1 PEKERJAAN INSTALASI LISTRIK",
            "section_group": "1 PEKERJAAN INSTALASI LISTRIK",
            "section_name": "1 PEKERJAAN INSTALASI LISTRIK",
            "activity_name": "1 Gang 1 Way Switch",
            "volume": "10.00",
            "unit": "unit",
            "selected_material_id": null,
            "current_unit_price": "115000.0000",
            "total_price": "1150000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "119",
            "construction_id": "44",
            "roman_number": "V",
            "group_name": "MEP",
            "sub_group_name": "1 PEKERJAAN INSTALASI LISTRIK",
            "section_group": "1 PEKERJAAN INSTALASI LISTRIK",
            "section_name": "1 PEKERJAAN INSTALASI LISTRIK",
            "activity_name": "2 Gang 1 Way Switch",
            "volume": "2.00",
            "unit": "unit",
            "selected_material_id": null,
            "current_unit_price": "115000.0000",
            "total_price": "230000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "120",
            "construction_id": "44",
            "roman_number": "V",
            "group_name": "MEP",
            "sub_group_name": "1 PEKERJAAN INSTALASI LISTRIK",
            "section_group": "1 PEKERJAAN INSTALASI LISTRIK",
            "section_name": "1 PEKERJAAN INSTALASI LISTRIK",
            "activity_name": "Single GPO - Broco",
            "volume": "10.00",
            "unit": "unit",
            "selected_material_id": null,
            "current_unit_price": "115000.0000",
            "total_price": "1150000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "121",
            "construction_id": "44",
            "roman_number": "V",
            "group_name": "MEP",
            "sub_group_name": "1 PEKERJAAN INSTALASI LISTRIK",
            "section_group": "1 PEKERJAAN INSTALASI LISTRIK",
            "section_name": "1 PEKERJAAN INSTALASI LISTRIK",
            "activity_name": "Double GPO - Broco",
            "volume": "2.00",
            "unit": "unit",
            "selected_material_id": null,
            "current_unit_price": "115000.0000",
            "total_price": "230000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "122",
            "construction_id": "44",
            "roman_number": "V",
            "group_name": "MEP",
            "sub_group_name": "2 PEKERJAAN SANITASI",
            "section_group": "2 PEKERJAAN SANITASI",
            "section_name": "2 PEKERJAAN SANITASI",
            "activity_name": "Pipa air bersih 3/4 inch",
            "volume": "50.00",
            "unit": "m'",
            "selected_material_id": null,
            "current_unit_price": "75000.0000",
            "total_price": "3750000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "123",
            "construction_id": "44",
            "roman_number": "V",
            "group_name": "MEP",
            "sub_group_name": "2 PEKERJAAN SANITASI",
            "section_group": "2 PEKERJAAN SANITASI",
            "section_name": "2 PEKERJAAN SANITASI",
            "activity_name": "Shower",
            "volume": "1.00",
            "unit": "unit",
            "selected_material_id": null,
            "current_unit_price": "2500000.0000",
            "total_price": "2500000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "124",
            "construction_id": "44",
            "roman_number": "V",
            "group_name": "MEP",
            "sub_group_name": "2 PEKERJAAN SANITASI",
            "section_group": "2 PEKERJAAN SANITASI",
            "section_name": "2 PEKERJAAN SANITASI",
            "activity_name": "Jet shower + closet duduk",
            "volume": "1.00",
            "unit": "unit",
            "selected_material_id": null,
            "current_unit_price": "3500000.0000",
            "total_price": "3500000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "125",
            "construction_id": "44",
            "roman_number": "V",
            "group_name": "MEP",
            "sub_group_name": "2 PEKERJAAN SANITASI",
            "section_group": "2 PEKERJAAN SANITASI",
            "section_name": "2 PEKERJAAN SANITASI",
            "activity_name": "Washtafel",
            "volume": "1.00",
            "unit": "unit",
            "selected_material_id": null,
            "current_unit_price": "2000000.0000",
            "total_price": "2000000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "126",
            "construction_id": "44",
            "roman_number": "V",
            "group_name": "MEP",
            "sub_group_name": "2 PEKERJAAN SANITASI",
            "section_group": "2 PEKERJAAN SANITASI",
            "section_name": "2 PEKERJAAN SANITASI",
            "activity_name": "Kran Air",
            "volume": "4.00",
            "unit": "unit",
            "selected_material_id": null,
            "current_unit_price": "150000.0000",
            "total_price": "600000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "127",
            "construction_id": "44",
            "roman_number": "V",
            "group_name": "MEP",
            "sub_group_name": "2 PEKERJAAN SANITASI",
            "section_group": "2 PEKERJAAN SANITASI",
            "section_name": "2 PEKERJAAN SANITASI",
            "activity_name": "Floordrain",
            "volume": "1.00",
            "unit": "unit",
            "selected_material_id": null,
            "current_unit_price": "150000.0000",
            "total_price": "150000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "128",
            "construction_id": "44",
            "roman_number": "V",
            "group_name": "MEP",
            "sub_group_name": "2 PEKERJAAN SANITASI",
            "section_group": "2 PEKERJAAN SANITASI",
            "section_name": "2 PEKERJAAN SANITASI",
            "activity_name": "Kitchen zink",
            "volume": "1.00",
            "unit": "unit",
            "selected_material_id": null,
            "current_unit_price": "700000.0000",
            "total_price": "700000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "129",
            "construction_id": "44",
            "roman_number": "V",
            "group_name": "MEP",
            "sub_group_name": "2 PEKERJAAN SANITASI",
            "section_group": "2 PEKERJAAN SANITASI",
            "section_name": "2 PEKERJAAN SANITASI",
            "activity_name": "Pipa air hujan 3 inch",
            "volume": "50.00",
            "unit": "m'",
            "selected_material_id": null,
            "current_unit_price": "80000.0000",
            "total_price": "4000000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "130",
            "construction_id": "44",
            "roman_number": "V",
            "group_name": "MEP",
            "sub_group_name": "2 PEKERJAAN SANITASI",
            "section_group": "2 PEKERJAAN SANITASI",
            "section_name": "2 PEKERJAAN SANITASI",
            "activity_name": "Pipa air kotor 2 inch",
            "volume": "50.00",
            "unit": "m'",
            "selected_material_id": null,
            "current_unit_price": "80000.0000",
            "total_price": "4000000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "131",
            "construction_id": "44",
            "roman_number": "V",
            "group_name": "MEP",
            "sub_group_name": "2 PEKERJAAN SANITASI",
            "section_group": "2 PEKERJAAN SANITASI",
            "section_name": "2 PEKERJAAN SANITASI",
            "activity_name": "Pipa air kotor 4 inch",
            "volume": "50.00",
            "unit": "m'",
            "selected_material_id": null,
            "current_unit_price": "80000.0000",
            "total_price": "4000000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "132",
            "construction_id": "44",
            "roman_number": "V",
            "group_name": "MEP",
            "sub_group_name": "2 PEKERJAAN SANITASI",
            "section_group": "2 PEKERJAAN SANITASI",
            "section_name": "2 PEKERJAAN SANITASI",
            "activity_name": "Septictank+ Resapan",
            "volume": "1.00",
            "unit": "unit",
            "selected_material_id": null,
            "current_unit_price": "5000000.0000",
            "total_price": "5000000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        },
        {
            "id": "133",
            "construction_id": "44",
            "roman_number": "V",
            "group_name": "MEP",
            "sub_group_name": "2 PEKERJAAN SANITASI",
            "section_group": "2 PEKERJAAN SANITASI",
            "section_name": "2 PEKERJAAN SANITASI",
            "activity_name": "Tandon Air 1000L",
            "volume": "1.00",
            "unit": "unit",
            "selected_material_id": null,
            "current_unit_price": "2000000.0000",
            "total_price": "2000000.0000",
            "is_locked": "0",
            "created_at": "2026-06-17 10:04:33",
            "updated_at": "2026-06-17 10:04:33",
            "image_url": null,
            "materials": []
        }
    ]
} 
JSON;
            $rabResponse = json_decode($jsonString, true);
            $rabData = $rabResponse['data'] ?? [];

            return $this->respond([
                'status' => true,
                'message' => empty($rabData) ? 'Belum ada RAB untuk permohonan konstruksi ini' : 'Data RAB permohonan konstruksi berhasil ditemukan',
                'data' => $rabData
            ]);

        } catch (\Throwable $th) {
            return $this->fail('Gagal mendapatkan data RAB: ' . $th->getMessage());
        }
    }
}
